export const NOTES_LIST_REQUEST = "NOTES_LIST_REQUEST"
export const NOTES_LIST_SUCCESS = "NOTES_LIST_SUCCESS"
export const NOTES_LIST_FAILED = "NOTES_LIST_FAILED"

export const NOTES_CREATE_REQUEST = "NOTES_CREATE_REQUEST"
export const NOTES_CREATE_SUCCESS = "NOTES_CREATE_SUCCESS"
export const NOTES_CREATE_FAILED = "NOTES_CREATE_FAILED"